name: Build and Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            # Step
            - name: Install npm dependencies
              # Action
              run: npm install
            # Step
            # this step is to test on localhost, after we conect our app with render
            - name: Change config
              run: echo "export const settings = { host:\"http://localhost:3030\" }" > config.js
            - name: Start the BE
              # Action and add &
              run: npm run start-be &
            - name:
                  Start FE
                  # Add &
              run: npm run start-fe &
            - name: Install Playwright
              run: npx playwright install
            - name: Start UI tests
              run: npm run test:ui
    deploy-BE:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: build_and_test
        steps:
            - name: Deploy to production
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{secrets.BACKEND_API_KEY}}
                  api-key: ${{secrets.RENDER_KEY}}
            - name: Sleep for 60 sec
              run: sleep 60
    deploy-FE:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: deploy-BE
        steps:
            - name: Deploy to production
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{secrets.FRONTEND_API_KEY}}
                  api-key: ${{secrets.RENDER_KEY}}
            - name: Sleep for 60 sec
              run: sleep 60
